# Generated by Django 5.1.4 on 2025-01-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_handover',
            field=models.BooleanField(default=False),
        ),
    ]
