# Generated by Django 5.1.4 on 2025-01-05 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_app', '0003_ticket_attachment_assignedticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='assigned_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='AssignedTicket',
        ),
    ]
